apiVersion: v1
kind: Secret
metadata: 
  name: secrets-cast
type: Opaque
data:
  POSTGRES_USER: Y2FzdF9kYl91c2VybmFtZQ==        # cast_db_username   base64 encoded
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==    # cast_db_password   base64 encoded
  POSTGRES_DB: Y2FzdF9kYl9kZXY=                  # cast_db_dev        base64 encoded