apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  labels:
    app: cast-db
spec:
  serviceName: cast-db
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - image: postgres:12.1-alpine      
          name: cast-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-cast     # The secret name must match the name of the secret created in the secrets-cast.yaml file.
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-cast
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets-cast    
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432     # from Postgres documentation
              protocol: TCP
          volumeMounts:
            - name: castdb-pvc       # PVC name must match the volumeMount name in the volumeClaimTemplates below.
              mountPath: /var/lib/postgresql/data/     
  volumeClaimTemplates:
  - metadata:
      name: castdb-pvc       # PVC name must match the volumeMount name above.
    spec:
      accessModes: [ "ReadWriteOnce" ]    # ReadWriteOnce is the only access mode supported by AWS EBS volumes.
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: cast-db
  labels:
    app: cast-db
spec:
  ports:
  - port: 5432
    name: cast-db
  clusterIP: None    # Headless
  selector:
    app: cast-db
